CourseWork/Controllers/DishesController.cs
using System.Linq;
using System.Threading.Tasks;
using CourseWork.Models;
using CourseWork.Models.Tables;
using CourseWork.ViewModels;
using CourseWork.ViewModels.Sorts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CourseWork.Controllers
{
    [Authorize]
    public class DishesController : Controller
    {
        private const int PageSize = 20;

        private readonly RestarauntDbContext _context;

        public DishesController(RestarauntDbContext context)
        {
            _context = context;
        }

        private static IQueryable<Dish> SortItems(IQueryable<Dish> items, Dish.Sort? sort)
        {
            return sort switch
            {
                Dish.Sort.NameAsc => items.OrderBy(o => o.Name),
                Dish.Sort.NameDesc => items.OrderByDescending(o => o.Name),
                Dish.Sort.CostAsc => items.OrderBy(o => o.Cost),
                Dish.Sort.CostDesc => items.OrderByDescending(o => o.Cost),
                Dish.Sort.CookingTimeAsc => items.OrderBy(o => o.CookingTime),
                Dish.Sort.CookingTimeDesc => items.OrderByDescending(o => o.CookingTime),
                Dish.Sort.OrderAsc => items.OrderBy(o => o.Order.Date.Date).ThenBy(o => o.Order.Time.TimeOfDay),
                Dish.Sort.OrderDesc => items.OrderByDescending(o => o.Order.Date.Date)
                    .ThenByDescending(o => o.Order.Time.TimeOfDay),
                _ => items
            };
        }

        // GET: Dishes
        public async Task<IActionResult> Index(int page = 1, Dish.Sort? sort = null)
        {
            IQueryable<Dish> items = _context.Dishes
                .Include(d => d.Order);
            var count = items.Count();
            items = SortItems(items, sort);
            items = items
                .Skip((page - 1) * PageSize)
                .Take(PageSize);
            return View(new DishViewModel
            {
                Items = await items.ToListAsync(),
                PageViewModel = new PageViewModel(count, page, PageSize),
                ItemsSort = new DishSort(sort)
            });
        }

        // GET: Dishes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();

            var dish = await _context.Dishes
                .Include(d => d.Order)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dish == null) return NotFound();

            return View(dish);
        }

        // GET: Dishes/Create
        public IActionResult Create()
        {
            ViewData["OrderId"] = new SelectList(_context.Orders, "Id", "DateTime");
            return View();
        }

        // POST: Dishes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Cost,CookingTime,OrderId")]
            Dish dish)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dish);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["OrderId"] = new SelectList(_context.Orders, "Id", "DateTime", dish.OrderId);
            return View(dish);
        }

        // GET: Dishes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            var dish = await _context.Dishes.FindAsync(id);
            if (dish == null) return NotFound();
            ViewData["OrderId"] = new SelectList(_context.Orders, "Id", "DateTime", dish.OrderId);
            return View(dish);
        }

        // POST: Dishes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Cost,CookingTime,OrderId")]
            Dish dish)
        {
            if (id != dish.Id) return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dish);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DishExists(dish.Id)) return NotFound();

                    throw;
                }

                return RedirectToAction(nameof(Index));
            }

            ViewData["OrderId"] = new SelectList(_context.Orders, "Id", "DateTime", dish.OrderId);
            return View(dish);
        }

        // GET: Dishes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            var dish = await _context.Dishes
                .Include(d => d.Order)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dish == null) return NotFound();

            return View(dish);
        }

        // POST: Dishes/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var dish = await _context.Dishes.FindAsync(id);
            _context.Dishes.Remove(dish);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DishExists(int id)
        {
            return _context.Dishes.Any(e => e.Id == id);
        }
    }
}

CourseWork/Controllers/OrdersController.cs
using System.Linq;
using System.Threading.Tasks;
using CourseWork.Models;
using CourseWork.Models.Tables;
using CourseWork.ViewModels;
using CourseWork.ViewModels.Filters;
using CourseWork.ViewModels.Sorts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CourseWork.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private const int PageSize = 20;

        private readonly RestarauntDbContext _context;

        public OrdersController(RestarauntDbContext context)
        {
            _context = context;
        }

        private static IQueryable<Order> SortItems(IQueryable<Order> items, Order.Sort? sort)
        {
            return sort switch
            {
                Order.Sort.DateAsc => items.OrderBy(o => o.Date),
                Order.Sort.DateDesc => items.OrderByDescending(o => o.Date),
                Order.Sort.TimeAsc => items.OrderBy(o => o.Time),
                Order.Sort.TimeDesc => items.OrderByDescending(o => o.Time),
                Order.Sort.CostAsc => items.OrderBy(o => o.Cost),
                Order.Sort.CostDesc => items.OrderByDescending(o => o.Cost),
                Order.Sort.PaymentAsc => items.OrderBy(o => o.Payment),
                Order.Sort.PaymentDesc => items.OrderByDescending(o => o.Payment),
                Order.Sort.CompletedAsc => items.OrderBy(o => o.Completed),
                Order.Sort.CompletedDesc => items.OrderByDescending(o => o.Completed),
                Order.Sort.CustomerAsc => items.OrderBy(o => o.Customer.Surname).ThenBy(o => o.Customer.Name),
                Order.Sort.CustomerDesc => items.OrderByDescending(o => o.Customer.Surname)
                    .ThenByDescending(o => o.Customer.Name),
                Order.Sort.EmployeeAsc => items.OrderBy(o => o.Employee.Surname).ThenBy(o => o.Employee.Name),
                Order.Sort.EmployeeDesc => items.OrderByDescending(o => o.Employee.Surname)
                    .ThenByDescending(o => o.Employee.Name),
                _ => items
            };
        }

        // GET: Orders
        public async Task<IActionResult> Index(int? selectedEmployeeIndex, int? dishCount, int? selectedDishIndex,
            int? selectedPaymentTypeIndex, int page = 1, Order.Sort? sort = null)
        {
            IQueryable<Order> items = _context.Orders
                .Include(o => o.Customer)
                .Include(o => o.Employee);

            if (selectedEmployeeIndex.HasValue && selectedEmployeeIndex.Value != 0)
                items = items.Where(o => o.Employee.Id == selectedEmployeeIndex);

            if (dishCount.HasValue) items = items.Where(o => o.Dishes.Count == dishCount);

            if (selectedDishIndex.HasValue && selectedDishIndex.Value != 0)
                items = items.Where(o => o.Dishes.Any(d => d.Id == selectedDishIndex));

            if (selectedPaymentTypeIndex.HasValue && selectedPaymentTypeIndex.Value != 0)
            {
                var type = (Order.PaymentType) selectedPaymentTypeIndex.Value;
                items = items.Where(o => o.Payment == type);
            }

            var count = items.Count();
            items = SortItems(items, sort);
            items = items
                .Skip((page - 1) * PageSize)
                .Take(PageSize);
            return View(new OrderViewModel
            {
                Items = await items.ToListAsync(),
                PageViewModel = new PageViewModel(count, page, PageSize),
                ItemsSort = new OrderSort(sort),
                ItemsFilter = new OrderFilter(await _context.Employees.ToListAsync(), selectedEmployeeIndex, dishCount,
                    await _context.Dishes.ToListAsync(), selectedDishIndex, selectedPaymentTypeIndex)
            });
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();

            var order = await _context.Orders
                .Include(o => o.Customer)
                .Include(o => o.Employee)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null) return NotFound();

            return View(order);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "FullName");
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "Id", "FullName");
            return View();
        }

        // POST: Orders/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Date,Cost,Payment,Completed,CustomerId,EmployeeId")]
            Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "FullName", order.CustomerId);
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "Id", "FullName", order.EmployeeId);
            return View(order);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            var order = await _context.Orders.FindAsync(id);
            if (order == null) return NotFound();
            ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "FullName", order.CustomerId);
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "Id", "FullName", order.EmployeeId);
            return View(order);
        }

        // POST: Orders/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Date,Cost,Payment,Completed,CustomerId,EmployeeId")]
            Order order)
        {
            if (id != order.Id) return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.Id)) return NotFound();

                    throw;
                }

                return RedirectToAction(nameof(Index));
            }

            ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "FullName", order.CustomerId);
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "Id", "FullName", order.EmployeeId);
            return View(order);
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            var order = await _context.Orders
                .Include(o => o.Customer)
                .Include(o => o.Employee)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null) return NotFound();

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order = await _context.Orders.FindAsync(id);
            _context.Orders.Remove(order);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
            return _context.Orders.Any(e => e.Id == id);
        }
    }
}

CourseWork/Controllers/UsersController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CourseWork.Models.Identity;
using CourseWork.ViewModels.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CourseWork.Controllers
{
    [Authorize(Roles = Role.Admin)]
    public class UsersController : Controller
    {
        private readonly UserManager<User> _userManager;

        public UsersController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            IList<UserViewModel> users = new List<UserViewModel>();
            foreach (var user in _userManager.Users)
            {
                var roles = await _userManager.GetRolesAsync(user);
                var role = roles.FirstOrDefault(r => Role.Admin == r) ?? Role.User;
                users.Add(new UserViewModel {User = user, Role = role});
            }

            return View(users);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null || user.UserName.Equals(User.Identity.Name)) return RedirectToAction("Index");
            var roles = await _userManager.GetRolesAsync(user);
            var role = roles.FirstOrDefault(r => Role.Admin == r) ?? Role.User;
            switch (role)
            {
                case Role.Admin:
                    await _userManager.AddToRoleAsync(user, Role.User);
                    await _userManager.RemoveFromRoleAsync(user, Role.Admin);
                    break;
                case Role.User:
                    await _userManager.AddToRoleAsync(user, Role.Admin);
                    await _userManager.RemoveFromRoleAsync(user, Role.User);
                    break;
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user != null && !user.UserName.Equals(User.Identity.Name)) await _userManager.DeleteAsync(user);
            return RedirectToAction("Index");
        }
    }
}

CourseWork/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Сервис "Ресторан"</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Заказчики</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Заказы</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dishes" asp-action="Index">Блюда</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DishIngredients" asp-action="Index">Ингредиенты блюд</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ingredients" asp-action="Index">Ингредиенты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Providers" asp-action="Index">Поставщики</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Сотрудники</a>
                        </li>
                    }
                    @if (User.IsInRole(Role.Admin))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Пользователи</a>
                        </li>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        <form class="form-inline my-2 my-lg-0" method="post" asp-controller="Account" asp-action="Logout">
                            <input class="btn btn-outline-danger" type="submit" value="Выйти"/>
                        </form>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>

<main role="main" class="pb-3" style="margin-left: 2%; margin-right: 2%;">
    @RenderBody()
</main>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; Курсовая работа - 2020 - Евгений Прищеп
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<script type="text/javascript">
    $.validator.methods.range = function (value, element, param) {
        var globalizedValue = value.replace(",", ".");
        return this.optional(element) || (globalizedValue >= param[0] && globalizedValue <= param[1]);
    }
    $.validator.methods.number = function (value, element) {
        return this.optional(element) || /^-?(?:\d+|\d{1,3}(?:[\s\.,]\d{3})+)(?:[\.,]\d+)?$/.test(value);
    }
</script>
</body>
</html>